### ISSUE TITLE
Create dedicated settings panel

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-core#23]
As discussed, we really need to move to a situation where the Kapow Core plugin has a settings panel, similar to the way Jetpack's settings work, where the various features of the plugin can be toggled on/off.

Preferably this will be written in React on the front-end.

**Comment by davetgreen** [comment]
@mattwatsoncodes I feel this is m00t now, given that we've curated what **should** be in this plugin?

**Comment by mattwatsoncodes** [comment]
Agreed @davetgreen, as with the new setup we can just comment out what we want without worrying about it.
